<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Crolow.Designer.Abstractions\Crolow.Designer.Common.csproj" />
  </ItemGroup>

</Project>
