<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.74.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.Arc" Version="4.74.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.74.1" />
    <PackageReference Include="Fluent.Ribbon" Version="11.0.2" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.4" />
    <PackageReference Include="Svg.Skia" Version="5.0.0" />
  </ItemGroup>

</Project>
